repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace # Убирает лишние пробелы
    - id: end-of-file-fixer # Добавляет пустую строку в конце файла
    - id: check-yaml # Проверяет синтаксис .yaml файлов
    - id: check-added-large-files # Проверяет, не добавляются ли большие файлы.
      args: ['--maxkb=300']  # максимальный размер добавляемого файла 300 кБ
    - id: check-merge-conflict # Проверяет, нет ли файлов, содержащих конфликтующие строки слияния.

# Отсортировывает импорты в проекте
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: __init__.py
        args: [ --profile, black, --filter-files, --line-length=79]

# Форматирует код под PEP8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        exclude: __init__.py

# Сканер стилистических ошибок, нарушающих договоренности PEP8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: __init__.py, */migrations/
        args: [ "--ignore=E501,F821" ]

# Линтер black
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.10
      exclude: ^migrations/
      args:
        - --line-length=79
        - --include=src/
